In [1]:
import numpy as np
import cPickle as pickle

import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
n_experiments = 8
files = []
for n in range(n_experiments):
    files.append('recall'+str(n+1)+'_f1')
    files.append('recall'+str(n+1)+'_f2')
    
results = []
for n in range(n_experiments):
    f1 = 'recall'+str(n+1)+'_f1'
    f2 = 'recall'+str(n+1)+'_f2'
    print f1,f2
    result1 = pickle.load(open(f1,'rb'))
    result2 = pickle.load(open(f2,'rb'))
    print (np.asarray(result1)+np.asarray(result2))/2

recall1_f1 recall1_f2
[ 0.40940013  0.57361302  0.66965049]
recall2_f1 recall2_f2
[ 0.40933132  0.56991461  0.666861  ]
recall3_f1 recall3_f2
[ 0.41563026  0.57786883  0.67550176]
recall4_f1 recall4_f2
[ 0.41787082  0.58155358  0.67875478]
recall5_f1 recall5_f2
[ 0.33059932  0.48970574  0.59739939]
recall6_f1 recall6_f2
[ 0.38051315  0.53443541  0.63156808]
recall7_f1 recall7_f2
[ 0.31451298  0.46883457  0.57512468]
recall8_f1 recall8_f2
[ 0.42759637  0.59342839  0.68566545]
