In [2]:
import numpy as np
import cPickle as pickle

import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
n_experiments = 15

for n in range(n_experiments):
    f = 'recall'+str(n+1)
    print f
    result = pickle.load(open(f,'rb'))
    print np.round(result,4)

recall1
[ 0.3783  0.5321  0.6143]
recall2
[ 0.4182  0.5815  0.682 ]
recall3
[ 0.4044  0.5631  0.6522]
recall4
[ 0.4184  0.5792  0.6756]
recall5
[ 0.4204  0.5831  0.6746]
recall6
[ 0.4217  0.5859  0.6787]
recall7
[ 0.4245  0.581   0.6786]
recall8
[ 0.4139  0.5768  0.6688]
recall9
[ 0.4189  0.5758  0.6757]
recall10
[ 0.4189  0.5753  0.6758]
recall11
[ 0.4197  0.5822  0.679 ]
recall12
[ 0.4141  0.5803  0.676 ]
recall13
[ 0.4211  0.5811  0.6808]
recall14
[ 0.4167  0.5816  0.6775]
recall15
[ 0.4112  0.5765  0.6727]
